// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq/zmq/mq.proto

#ifndef PROTOBUF_INCLUDED_mq_2fzmq_2fmq_2eproto
#define PROTOBUF_INCLUDED_mq_2fzmq_2fmq_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mq_2fzmq_2fmq_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_mq_2fzmq_2fmq_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
namespace protocol {
class MQMessage;
class MQMessageDefaultTypeInternal;
extern MQMessageDefaultTypeInternal _MQMessage_default_instance_;
}  // namespace protocol
namespace google {
namespace protobuf {
template<> ::protocol::MQMessage* Arena::CreateMaybeMessage<::protocol::MQMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace protocol {

// ===================================================================

class MQMessage final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:protocol.MQMessage) */ {
 public:
  MQMessage();
  virtual ~MQMessage();

  MQMessage(const MQMessage& from);

  inline MQMessage& operator=(const MQMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MQMessage(MQMessage&& from) noexcept
    : MQMessage() {
    *this = ::std::move(from);
  }

  inline MQMessage& operator=(MQMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const MQMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MQMessage* internal_default_instance() {
    return reinterpret_cast<const MQMessage*>(
               &_MQMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MQMessage* other);
  friend void swap(MQMessage& a, MQMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MQMessage* New() const final {
    return CreateMaybeMessage<MQMessage>(nullptr);
  }

  MQMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MQMessage>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const MQMessage& from);
  void MergeFrom(const MQMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MQMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string extension = 4;
  void clear_extension();
  static const int kExtensionFieldNumber = 4;
  const ::std::string& extension() const;
  void set_extension(const ::std::string& value);
  #if LANG_CXX11
  void set_extension(::std::string&& value);
  #endif
  void set_extension(const char* value);
  void set_extension(const char* value, size_t size);
  ::std::string* mutable_extension();
  ::std::string* release_extension();
  void set_allocated_extension(::std::string* extension);

  // bytes payload = 5;
  void clear_payload();
  static const int kPayloadFieldNumber = 5;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  #if LANG_CXX11
  void set_payload(::std::string&& value);
  #endif
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // uint32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // bool ack = 3;
  void clear_ack();
  static const int kAckFieldNumber = 3;
  bool ack() const;
  void set_ack(bool value);

  // @@protoc_insertion_point(class_scope:protocol.MQMessage)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr extension_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::uint32 type_;
  bool ack_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mq_2fzmq_2fmq_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MQMessage

// string id = 1;
inline void MQMessage::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MQMessage::id() const {
  // @@protoc_insertion_point(field_get:protocol.MQMessage.id)
  return id_.GetNoArena();
}
inline void MQMessage::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.MQMessage.id)
}
#if LANG_CXX11
inline void MQMessage::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.MQMessage.id)
}
#endif
inline void MQMessage::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.MQMessage.id)
}
inline void MQMessage::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.MQMessage.id)
}
inline ::std::string* MQMessage::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:protocol.MQMessage.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MQMessage::release_id() {
  // @@protoc_insertion_point(field_release:protocol.MQMessage.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MQMessage::set_allocated_id(::std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:protocol.MQMessage.id)
}

// uint32 type = 2;
inline void MQMessage::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 MQMessage::type() const {
  // @@protoc_insertion_point(field_get:protocol.MQMessage.type)
  return type_;
}
inline void MQMessage::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:protocol.MQMessage.type)
}

// bool ack = 3;
inline void MQMessage::clear_ack() {
  ack_ = false;
}
inline bool MQMessage::ack() const {
  // @@protoc_insertion_point(field_get:protocol.MQMessage.ack)
  return ack_;
}
inline void MQMessage::set_ack(bool value) {
  
  ack_ = value;
  // @@protoc_insertion_point(field_set:protocol.MQMessage.ack)
}

// string extension = 4;
inline void MQMessage::clear_extension() {
  extension_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MQMessage::extension() const {
  // @@protoc_insertion_point(field_get:protocol.MQMessage.extension)
  return extension_.GetNoArena();
}
inline void MQMessage::set_extension(const ::std::string& value) {
  
  extension_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.MQMessage.extension)
}
#if LANG_CXX11
inline void MQMessage::set_extension(::std::string&& value) {
  
  extension_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.MQMessage.extension)
}
#endif
inline void MQMessage::set_extension(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  extension_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.MQMessage.extension)
}
inline void MQMessage::set_extension(const char* value, size_t size) {
  
  extension_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.MQMessage.extension)
}
inline ::std::string* MQMessage::mutable_extension() {
  
  // @@protoc_insertion_point(field_mutable:protocol.MQMessage.extension)
  return extension_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MQMessage::release_extension() {
  // @@protoc_insertion_point(field_release:protocol.MQMessage.extension)
  
  return extension_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MQMessage::set_allocated_extension(::std::string* extension) {
  if (extension != nullptr) {
    
  } else {
    
  }
  extension_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extension);
  // @@protoc_insertion_point(field_set_allocated:protocol.MQMessage.extension)
}

// bytes payload = 5;
inline void MQMessage::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MQMessage::payload() const {
  // @@protoc_insertion_point(field_get:protocol.MQMessage.payload)
  return payload_.GetNoArena();
}
inline void MQMessage::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:protocol.MQMessage.payload)
}
#if LANG_CXX11
inline void MQMessage::set_payload(::std::string&& value) {
  
  payload_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:protocol.MQMessage.payload)
}
#endif
inline void MQMessage::set_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:protocol.MQMessage.payload)
}
inline void MQMessage::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:protocol.MQMessage.payload)
}
inline ::std::string* MQMessage::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:protocol.MQMessage.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MQMessage::release_payload() {
  // @@protoc_insertion_point(field_release:protocol.MQMessage.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MQMessage::set_allocated_payload(::std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:protocol.MQMessage.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_mq_2fzmq_2fmq_2eproto
